BEGIN
   DECLARE CONTADOR_ID INT;

   SELECT IFNULL(MAX(ID_USUARIO), 0) + 1 INTO CONTADOR_ID
   FROM USUARIOS;

   INSERT INTO USUARIOS(ID_USUARIO, CODIGO, NOMBRES, APELLIDOS, MAIL, FECHA_NACIMIENTO, CONTRASENA, ESTADO, USUARIO_CREACION, FECHA_CREACION)
   VALUES(CONTADOR_ID, PV_CODIGO, PV_NOMBRES, PV_APELLIDOS, PV_MAIL, PD_FECHA_NACIMIENTO, PV_CONTRASENA, 'A', PI_USUARIO_CREACION, NOW());
END