BEGIN
   UPDATE USUARIOS
   SET 
      CODIGO = PV_CODIGO,
      NOMBRES = PV_NOMBRES,
      APELLIDOS = PV_APELLIDOS,
      MAIL = PV_MAIL,
      FECHA_NACIMIENTO = PD_FECHA_NACIMIENTO,
      CONTRASENA = PV_CONTRASENA,
      USUARIO_MODIFICACION = PI_USUARIO_MODIFICACION,
      FECHA_MODIFICACION = NOW()
   WHERE
      ID_USUARIO = PI_ID_USUARIO;
END